import type {
  CampaignStatus,
  ClaimStatus,
  DealStatus,
  PayoutStatus,
  TransactionType,
} from '../../shared/types';

export const en = {
  brand: 'LocalLoop',
  demoMode: 'Demo mode',
  backToProduct: 'Back to the LocalLoop app',
  demoLauncherTitle: 'Local B2B rewards network',
  demoLauncherBody:
    'Pick a persona and walk the Magnolia × Camora demo from one shared server state.',
  openCustomer: 'Customer — Nino',
  openAdvertiser: 'Advertiser — Magnolia',
  openHost: 'Host — Camora',
  reset: 'Reset demo',
  loading: 'Loading…',
  errorGeneric: 'Something went wrong. Please try again.',
  emptyState: 'Nothing to show here yet.',
  workspaceAdvertiser: 'Advertiser workspace',
  workspaceHost: 'Host workspace',
  businessWorkspace: 'Business workspace',
  personaNino: 'Nino',
  personaMagnolia: 'Magnolia Film Lab',
  personaCamora: 'Camora',
  campaignName: 'Develop the Night',
  fundAction: 'Simulate campaign funding',
  verifyVisit: 'Verify Camora visit',
  redeemRequest: 'Request reward redemption',
  validateRedemption: 'Validate redemption',
  fundingLabel: 'Simulated budget',
  settlementLabel: 'Demo settlement on Solana devnet',
  capabilityMissing: 'This business does not have the requested capability.',
  revisionLabel: 'Revision',
  openExplorer: 'Open in Explorer',
  noReceipt: 'No transaction receipt yet.',
  connectWallet: 'Connect wallet',
  disconnectWallet: 'Disconnect',
  signAndFund: 'Sign authorization & simulate funding',
  walletConnected: 'Connected',
  walletUnsupported:
    'This wallet cannot sign messages. Connect a Wallet Standard wallet that supports signMessage.',
  phantomNotDetected:
    'Phantom is not available in this browser. Open this page in the browser where the Phantom extension is installed and unlocked, then try again.',
  walletConnectionTimedOut:
    'Phantom did not finish connecting. Unlock the extension, approve the connection, and try again.',
  challengePreview: 'Exact authorization message',
  fundingPending: 'Submitting funding proof on Solana devnet…',
  fundingSuccess: 'Campaign marked simulated-funded after confirmed proof.',
  fundingDisclosure:
    'No SOL leaves your connected wallet. You only sign a message. The server demo treasury records a memo on Solana devnet.',
  solanaNotReady:
    'Solana is not configured. Add DEMO_TREASURY_SECRET_KEY and DEMO_HOST_PUBLIC_KEY to .env, keep SOLANA_CLUSTER=devnet, fund the treasury via the faucet, then retry.',
  approveDeal: 'Approve deal',
  approveDealDisabled: 'Approve unlocks after simulated funding.',
  hostEmptyAdvertiser:
    'No advertiser campaigns for this business in the demo seed.',
  advertiserEmptyHost:
    'No host deals for this business in the demo seed. Switch to advertiser workspace for Magnolia’s campaign.',
  dealTerms: 'Deal terms',
  partnerDeals: 'Partner deals',
  budgetTotal: 'Total',
  budgetReserved: 'Reserved',
  budgetPaid: 'Paid',
  budgetRemaining: 'Remaining',
  rewardTerms: 'Reward',
  claimId: 'Claim ID',
  visitsProgress: 'Verified visits',
  payoutStatus: 'Payout',
  retryPayout: 'Retry payout',
  oneTimeUse: 'One-time reward — redeem once at Magnolia.',
  staffMode: 'Staff verification mode',
  qrPlacement: 'LocalLoop QR / pass placement (demo visual — no camera)',
  incomingRedemption: 'Incoming redemption',
  noRedemption: 'No redemption request yet.',
  mockedDeal: 'Mocked partner path',
  workingDeal: 'Live demo path',
  continue: 'Continue',
  useReward: 'Use reward at Magnolia',
  declineReward: 'Don’t use this reward',
  waitingOnHost: 'Waiting for Camora to verify your visits.',
  waitingOnFunding: 'Waiting for Magnolia to simulate campaign funding.',
  waitingOnCustomer: 'Waiting for Nino to use or decline the reward.',
  waitingOnApproval: 'Waiting for Camora to approve the deal.',
  waitingOnRedemption: 'Waiting for Nino to request redemption at Magnolia.',
  budgetUnchanged: 'Campaign budget unchanged — no host payout.',
  declinedDone:
    'You kept the visits at Camora but did not use the Magnolia reward. No payout will be sent.',
  redemptionSent: 'Redemption requested. Magnolia will validate next.',
  wizard: {
    advertiser: {
      campaignTitle: 'Campaign',
      campaignHeadline: 'Develop the Night',
      campaignBody:
        'Magnolia runs a 0.05 SOL simulated budget to reward Camora guests with film-lab discounts.',
      fundTitle: 'Fund on Solana',
      fundHeadline: 'Authorize simulated funding',
      fundBody:
        'Sign a message only. The server treasury posts a real memo on Solana devnet.',
      hostsTitle: 'Hosts',
      hostsHeadline: 'Camora is your live host path',
      hostsBody:
        'One working deal with Camora. TSRE Gym stays a proposed mock partner.',
      redemptionTitle: 'Redemption',
      redemptionHeadline: 'Validate Nino’s reward',
      redemptionBody:
        'When Nino asks to use the discount at Magnolia, confirm it here.',
      redemptionWaitingHeadline: 'Waiting for redemption',
      redemptionWaitingBody:
        'Nino unlocks the reward after three Camora visits, then chooses to use or decline it.',
      redemptionDeclinedHeadline: 'Reward declined',
      redemptionDeclinedBody:
        'Nino did not use the Magnolia reward. Simulated budget stays at 0.05 SOL.',
      settleTitle: 'Settlement',
      settlePaidHeadline: 'Host payout confirmed',
      settlePaidBody:
        'Server treasury sent 0.005 SOL to Camora on Solana devnet.',
      settleDeclinedHeadline: 'No payout',
      settleDeclinedBody:
        'Because the reward was not used, advertiser budget did not change.',
    },
    host: {
      dealTitle: 'Incoming deal',
      dealHeadline: 'Magnolia wants Camora as host',
      dealBody:
        '3 verified visits unlock a Magnolia film reward. Host payout is 0.005 SOL on success.',
      visitsTitle: 'Verify visits',
      visitsHeadline: 'Staff verification',
      visitsBody: 'Confirm each qualifying Camora visit for Nino.',
      earningsTitle: 'Earnings',
      earningsWaitingHeadline: 'Waiting on customer',
      earningsWaitingBody:
        'After the reward unlocks, Nino chooses to use it at Magnolia or decline.',
      earningsPaidHeadline: 'Paid on Solana devnet',
      earningsPaidBody: '0.005 SOL arrived from the server demo treasury.',
      earningsDeclinedHeadline: 'No payout this time',
      earningsDeclinedBody:
        'Nino still visited Camora — you earned the foot traffic, but no campaign payout.',
    },
    customer: {
      dealTitle: 'Your deal',
      dealHeadline: 'Camora × Magnolia',
      dealBody:
        'Complete three verified visits at Camora to unlock 10 ₾ off film development at Magnolia.',
      progressTitle: 'Progress',
      progressHeadline: 'Visit Camora',
      progressBody: 'Camora staff verify each visit. You’re already at 1 of 3.',
      unlockedTitle: 'Reward unlocked',
      unlockedHeadline: 'Ready at Magnolia',
      unlockedBody:
        'Your one-time reward is unlocked. Use it at Magnolia or leave it.',
      chooseTitle: 'Choose',
      chooseHeadline: 'Use the reward?',
      chooseBody:
        'Using it lets Magnolia validate and pays Camora 0.005 SOL. Declining leaves the budget unchanged.',
      doneTitle: 'Done',
      doneUsedHeadline: 'Redemption in progress',
      doneUsedBody: 'Magnolia will validate your request next.',
      doneRedeemedHeadline: 'Reward redeemed',
      doneRedeemedBody: 'Thanks — Camora’s payout can settle on Solana devnet.',
      doneDeclinedHeadline: 'Reward not used',
      doneDeclinedBody:
        'No Magnolia purchase and no host payout. Your Camora visits still happened.',
    },
  },

  /* ---------------------------------------------------------------- */
  /* Product app (mocked): landing, auth, customer, business           */
  /* ---------------------------------------------------------------- */

  shell: {
    skipToContent: 'Skip to content',
    signIn: 'Sign in',
    getStarted: 'Get started',
    signOut: 'Sign out',
    signedInAs: 'Signed in as',
    customerNav: 'Deals',
    businessNav: 'Dashboard',
    mockBadge: 'Mock data',
    mockNote:
      'Everything on these screens is mock data held in this browser. No wallet, no server, no blockchain.',
    footerBuild: 'Build',
    footerLang: 'Lang',
    footerLayer: 'Layer',
    footerLayerProduct: 'Product / mocked',
    footerLive: 'Solana devnet demo',
    footerDocs: 'Design language',
  },

  landing: {
    metaIndex: 'Index 01—04',
    status: 'Tbilisi pilot',
    eyebrow: 'Local rewards network',
    title: 'Neighbouring businesses, wired into one reward loop',
    lede:
      'A business funds a reward. The shop next door sends customers to earn it. The customer redeems it. Every payout is settled against the funding business’s campaign budget.',
    heroPrimary: 'Create an account',
    heroSecondary: 'See how it works',
    heroMeta: '8 Egnate Ninoshvili Street · Tbilisi',
    loopFigure: 'The reward loop',
    loopDescription:
      'A loop diagram: the advertiser funds a campaign, the host verifies customer visits, the customer redeems the reward with the advertiser, and the advertiser pays the host per redemption.',
    loopNodes: {
      advertiserTitle: 'Advertiser',
      advertiserCaption: 'Funds the campaign',
      hostTitle: 'Host',
      hostCaption: 'Verifies the visits',
      customerTitle: 'Customer',
      customerCaption: 'Earns the reward',
    },
    loopEdges: {
      advertiserToHost: 'Offers a deal',
      hostToCustomer: 'Verifies visits',
      customerToAdvertiser: 'Redeems, host gets paid',
    },
    sections: {
      how: 'How the loop runs',
      sides: 'Two sides of LocalLoop',
      roles: 'Host and advertiser are states, not accounts',
      start: 'Start here',
    },
    howBody:
      'One campaign connects two businesses and one customer. Each step is a state the whole network can see.',
    steps: [
      {
        index: '01',
        title: 'A campaign is funded',
        body: 'A business sets a budget and defines the perk it will give away.',
        meta: 'CAMPAIGN / LIVE',
      },
      {
        index: '02',
        title: 'A partner agrees to host',
        body: 'A nearby business accepts the deal and the visit requirement it will verify.',
        meta: 'DEAL / ACTIVE',
      },
      {
        index: '03',
        title: 'A customer collects visits',
        body: 'Visits at the host are verified until the reward requirement is met.',
        meta: 'CLAIM / LOCKED',
      },
      {
        index: '04',
        title: 'The reward is redeemed',
        body: 'The customer redeems with the advertiser and the host is paid per redemption.',
        meta: 'CLAIM / REDEEMED',
      },
    ],
    customerSide: {
      index: 'B',
      label: 'Customer',
      title: 'Collect visits, unlock rewards',
      body: 'Browse live deals from businesses near you, open a reward pass, collect the required visits at the host, then redeem with the business that funded the perk.',
      points: [
        'Browse every active deal in one index',
        'Track visit progress on a reward pass',
        'Redeem once the requirement is met',
      ],
      cta: 'Join as a customer',
    },
    businessSide: {
      index: 'C',
      label: 'Business',
      title: 'Run campaigns, host partners',
      body: 'One business account covers both directions: fund a campaign to bring in new customers, and host other businesses’ campaigns to earn a payout for every redemption you help create.',
      points: [
        'Create a campaign with a budget and partner deals',
        'Accept partnership requests from nearby businesses',
        'Validate redemptions and watch the budget ledger',
      ],
      cta: 'Join as a business',
    },
    rolesBody:
      'There is only one business account type. What you are called depends on what your business is currently doing.',
    advertiserRole: {
      label: 'Advertiser',
      definition: 'A business with an active campaign and a budget behind it.',
      detail:
        'You pay per redemption to the partners who send customers your way.',
    },
    customerRole: {
      label: 'Customer',
      definition: 'A person collecting verified visits to unlock a reward.',
    },
    hostRole: {
      label: 'Host',
      definition: 'A business that has accepted another campaign’s deal.',
      detail:
        'You verify customer visits and earn the deal payout for each redemption.',
    },
    rolesBoth:
      'Most businesses end up as both: hosting a neighbour’s campaign while running one of their own.',
    startBody: 'Pick a side. You can switch by creating a second account.',
    liveLink: 'Open the Solana devnet demo',
    liveLinkDetail:
      'The wallet-signed, server-settled version of this loop. Needs Phantom and a running API.',
  },

  auth: {
    chooseTitle: 'Create your account',
    chooseLede: 'Two account types. Pick the one that matches how you will use LocalLoop.',
    chooseCustomer: 'I’m a customer',
    chooseCustomerBody: 'Collect visits at local businesses and redeem rewards.',
    chooseBusiness: 'I’m a business',
    chooseBusinessBody:
      'Run reward campaigns, host partner campaigns, or both.',
    haveAccount: 'Already have an account?',
    signIn: 'Sign in',
    noAccount: 'Need an account?',
    register: 'Create one',
    registerCustomerTitle: 'Customer account',
    registerBusinessTitle: 'Business account',
    registerLede: 'Nothing is sent anywhere. The account lives in this browser.',
    loginTitle: 'Sign in',
    loginLede: 'Sign in as a customer or a business to open the matching view.',
    nameLabel: 'Your name',
    namePlaceholder: 'Nino Kapanadze',
    businessNameLabel: 'Business name',
    businessNamePlaceholder: 'Magnolia Film Lab',
    emailLabel: 'Email',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    accountTypeLabel: 'Account type',
    submitRegister: 'Create account',
    submitLogin: 'Sign in',
    working: 'Working…',
    required: 'Fill in every field to continue.',
    mockNote:
      'Mock authentication — no password is checked and no data leaves this browser.',
    backToLanding: 'Back to LocalLoop',
  },

  customerApp: {
    indexTitle: 'Live deals',
    indexLede:
      'Neighbourhood perks from nearby shops. Peek at the places involved, then open a deal to start.',
    indexSection: 'Near you',
    indexEmpty: 'No live deals right now. Check back once a shop publishes something new.',
    passesSection: 'Your passes',
    passesEmpty: 'You have not opened a reward pass yet.',
    columnAdvertiser: 'Reward from',
    columnHost: 'Go here',
    columnRequirement: 'To unlock',
    columnPerk: 'Reward',
    columnStatus: 'Status',
    placeVisit: 'Go here',
    placeReward: 'Reward from',
    linkMaps: 'Map',
    linkInstagram: 'Instagram',
    linkWebsite: 'Site',
    finePrint: 'Fine print',
    visits: (n: number) => `${n} verified ${n === 1 ? 'visit' : 'visits'}`,
    notStarted: 'Not started',
    expandDeal: 'More',
    collapseDeal: 'Less',
    openDeal: 'Start this deal',
    detailSection: 'Deal',
    criteriaSection: 'The deal',
    progressSection: 'Your progress',
    rewardSection: 'The reward',
    partnersSection: 'The shops',
    criteriaVisits: 'Visits needed',
    criteriaAction: 'What to do',
    criteriaHost: 'Where to go',
    criteriaPerk: 'What you get',
    criteriaConditions: 'Fine print',
    criteriaOneTime: 'One reward per customer',
    criteriaPayout: 'Shop payout per redemption',
    claimAction: 'Open reward pass',
    claimHint: 'Opening a pass starts tracking your progress.',
    visitAction: 'Check in here',
    visitHint:
      'Mock check-in. In the live product the shop verifies each visit from their own console.',
    actionAction: 'Mark as done',
    actionHint:
      'Mock confirmation. In the live product the shop verifies the tasting from their console.',
    visitsDone: 'All required visits done',
    actionDone: 'Done',
    actionPending: 'Not yet',
    redeemAction: 'Request redemption',
    redeemHint: 'Ask the reward shop to confirm you used it.',
    requestedTitle: 'Redemption requested',
    requestedBody:
      'The reward shop reviews the request and confirms it from their dashboard.',
    redeemedTitle: 'Reward redeemed',
    redeemedBody:
      'The partner shop earned its payout for this redemption against the campaign budget.',
    lockedTitle: 'Keep going',
    lockedBody: 'The reward unlocks once you finish the ask.',
    progressLabel: 'Progress',
    backToDeals: 'Back to deals',
    notFound: 'That deal is no longer available.',
  },

  businessApp: {
    dashboardSection: 'Business dashboard',
    dashboardLede:
      'Your campaigns, partnerships, and redemption queue in one panel.',
    identitySection: 'Identity',
    roleAdvertiser: 'Advertiser',
    roleHost: 'Host',
    roleNone: 'No active role yet',
    roleAdvertiserWhy: 'You run an active campaign with a budget.',
    roleHostWhy: 'You verify visits for another campaign.',
    roleNoneWhy:
      'Create a campaign to become an advertiser, or accept a partnership request to become a host.',
    metricsSection: 'Readings',
    metricCampaigns: 'Campaigns',
    metricBudget: 'Committed budget',
    metricHosted: 'Hosted deals',
    metricEarned: 'Earned as host',
    campaignsSection: 'Your campaigns',
    campaignsEmpty:
      'No campaigns yet. Create one to set a budget, choose partners, and go live.',
    createCampaign: 'Create campaign',
    ledgerLabel: 'Simulated budget ledger',
    ledgerPaid: 'Paid',
    ledgerReserved: 'Reserved',
    ledgerRemaining: 'Remaining',
    partnersLabel: 'Partners',
    requestsSection: 'Partnership requests',
    requestsLede: 'Campaigns asking your business to host their reward.',
    requestsEmpty: 'No partnership requests waiting.',
    requestAccept: 'Accept and host',
    requestDecline: 'Decline',
    requestTerms: 'Terms',
    hostingSection: 'Campaigns you host',
    hostingEmpty: 'Accept a request to start hosting.',
    hostingRedemptions: 'Redemptions helped',
    redemptionsSection: 'Redemption queue',
    redemptionsLede:
      'Customers asking to use a reward from one of your campaigns.',
    redemptionsEmpty:
      'Nothing waiting. Requests appear here when a customer redeems one of your rewards.',
    validate: 'Validate redemption',
    activitySection: 'Activity log',
    activityEmpty: 'Nothing has happened yet.',
    perRedemption: 'per redemption',
    maxRedemptions: 'max redemptions',
    visitsRequired: 'visits required',
  },

  campaignWizard: {
    title: 'Create a campaign',
    lede: 'Five steps: what you offer, the budget behind it, who hosts it, the deal terms, and a final check.',
    routeLabel: 'Campaign setup steps',
    back: 'Back',
    next: 'Continue',
    cancel: 'Cancel',
    publish: 'Publish campaign',
    stepIdentity: 'Offer',
    stepBudget: 'Budget',
    stepPartners: 'Partners',
    stepDeals: 'Deal terms',
    stepReview: 'Review',
    identityTitle: 'What are you offering?',
    identityBody:
      'Customers see this on the deal card and on their reward pass.',
    nameLabel: 'Campaign name',
    namePlaceholder: 'Develop the Night',
    perkLabel: 'The reward',
    perkPlaceholder: '10 ₾ off film development and scanning',
    conditionsLabel: 'Conditions',
    conditionsPlaceholder: 'Applies to orders over 40 ₾. One reward per customer.',
    budgetTitle: 'How much are you committing?',
    budgetBody:
      'Every redemption pays your host from this budget. The ledger below updates as you type.',
    budgetLabel: 'Campaign budget (SOL)',
    budgetWalletTitle: 'Funding wallet',
    budgetWalletDisconnected: 'No wallet connected',
    budgetWalletConnected: 'Mock wallet connected',
    budgetConnect: 'Connect wallet',
    budgetMockNote:
      'Mock wallet and simulated budget. No SOL moves and no transaction is signed here.',
    partnersTitle: 'Who will host your campaign?',
    partnersBody:
      'Pick the nearby businesses whose customers you want to reach. Each one gets its own deal.',
    partnersSearch: 'Search businesses',
    partnersSearchPlaceholder: 'Search by name…',
    partnersEmpty: 'No businesses match that search.',
    partnersSelected: 'Selected partners',
    partnersNone: 'Select at least one partner to continue.',
    add: 'Add',
    remove: 'Remove',
    dealsTitle: 'Set the deal for each partner',
    dealsBody:
      'The requirement is what the customer must do at the host. The payout is what the host earns per redemption.',
    dealVisits: 'Visits required',
    dealPayout: 'Payout per redemption (SOL)',
    dealMax: 'Maximum redemptions',
    dealCapacity: 'Committed capacity',
    dealOverBudget:
      'Committed capacity is above your budget. Lower the payout, the cap, or raise the budget.',
    reviewTitle: 'Check and publish',
    reviewBody:
      'Publishing makes the deal visible to customers straight away in this browser.',
    reviewOffer: 'Offer',
    reviewBudget: 'Budget',
    reviewPartners: 'Partner deals',
    published: 'Campaign published',
    validationName: 'Give the campaign a name, a reward, and conditions.',
    validationBudget: 'Set a budget above zero and connect the mock wallet.',
  },
} as const;

export const claimStatusLabel: Record<ClaimStatus, string> = {
  locked: 'Locked',
  unlocked: 'Unlocked',
  redemption_requested: 'Redemption requested',
  redeemed: 'Redeemed',
  declined: 'Declined',
};

export const payoutStatusLabel: Record<PayoutStatus, string> = {
  not_ready: 'Not ready',
  pending: 'Pending',
  processing: 'Processing',
  paid: 'Paid',
  failed: 'Failed',
};

export const campaignStatusLabel: Record<CampaignStatus, string> = {
  draft: 'Draft',
  simulated_funded: 'Simulated funded',
  live: 'Live',
  completed: 'Completed',
};

export const dealStatusLabel: Record<DealStatus, string> = {
  proposed: 'Proposed',
  active: 'Active',
  completed: 'Completed',
};

export const transactionTypeLabel: Record<TransactionType, string> = {
  funding_proof: 'Funding proof',
  host_payout: 'Host payout',
};
